const BOARD_SIZE_X = 8
const BOARD_SIZE_Y = 9
const ABOVE_BOUNDARY = 4
const BELOW_BOUNDARY = 5
const BELOW_TOP_CHAMPION_AREA = 7
const BELOW_BOT_CHAMPION_AREA = 9
const ABOVE_TOP_CHAMPION_AREA = 0
const ABOVE_BOT_CHAMPION_AREA = 2
const LEFT_CHAMPION_AREA = 3
const RIGHT_CHAMPION_AREA = 5

export { 
    BOARD_SIZE_X, 
    BOARD_SIZE_Y, 
    ABOVE_BOUNDARY, 
    BELOW_BOUNDARY, 
    BELOW_TOP_CHAMPION_AREA, 
    BELOW_BOT_CHAMPION_AREA, 
    ABOVE_TOP_CHAMPION_AREA, 
    ABOVE_BOT_CHAMPION_AREA, 
    LEFT_CHAMPION_AREA, 
    RIGHT_CHAMPION_AREA 
}